# Generated by Django 3.2.16 on 2023-01-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_cart_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='new_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
